<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
useSeoMeta({ title: 'Dokumentasi Pengguna | PPEPD', robots: 'noindex' })
const { can } = useAuth()
const local = useRuntimeConfig().public.localManagement
</script>

<template>
  <div class="space-y-6">
    <AccountNavigation />
    <header><p class="text-sm font-semibold text-klh-green-700">Panduan PPEPD</p><h1 class="mt-2 font-display text-3xl font-bold">Dokumentasi pengguna</h1><p class="mt-3 text-ink-500">Panduan mengakses aplikasi, memperbarui profil, dan mengelola akun sesuai hak akses Anda.</p></header>
    <nav class="flex flex-wrap gap-2" aria-label="Isi dokumentasi"><a href="#mulai" class="btn btn-outline">Mulai menggunakan</a><a href="#profil" class="btn btn-outline">Profil &amp; password</a><a v-if="local && can('users.manage')" href="#akun" class="btn btn-outline">Manajemen akun</a><a v-if="local && can('roles.manage')" href="#roles" class="btn btn-outline">Roles</a><a href="#bantuan" class="btn btn-outline">Bantuan</a></nav>
    <section id="mulai" class="klh-card scroll-mt-24 space-y-3 p-5 sm:p-8"><h2 class="font-display text-2xl font-bold">Mulai menggunakan aplikasi</h2><ol class="list-decimal space-y-2 pl-5"><li>Buka My Profiles setelah masuk.</li><li>Pilih aplikasi dari daftar atau gunakan pencarian.</li><li>Di ponsel, gunakan tombol halaman atau geser daftar untuk melihat aplikasi berikutnya.</li></ol><p class="text-ink-500">Daftar aplikasi dan navigasi mengikuti izin akun. Gunakan Beranda untuk kembali ke portal dan Keluar setelah selesai.</p><NuxtLink to="/my-profiles" class="btn btn-primary">Buka My Profiles</NuxtLink></section>
    <section id="profil" class="klh-card scroll-mt-24 space-y-3 p-5 sm:p-8"><h2 class="font-display text-2xl font-bold">Profil &amp; password</h2><p>Di My Profiles, pilih <strong>Profil &amp; password</strong>. Perbarui nama, instansi, atau organisasi, lalu pilih Simpan profil. Username dan email tidak dapat diubah dari profil pribadi.</p><p>Untuk mengganti password, masukkan password saat ini, password baru sepanjang 12–128 karakter, dan konfirmasinya. Setelah berhasil, sesi pada perangkat lain dicabut. Perangkat yang digunakan tetap masuk.</p><p class="text-ink-500">Gunakan frasa panjang yang mudah diingat. Jika lupa password saat ini, hubungi administrator untuk meminta reset.</p></section>
    <section v-if="local && can('users.manage')" id="akun" class="klh-card scroll-mt-24 space-y-3 p-5 sm:p-8"><h2 class="font-display text-2xl font-bold">Manajemen akun pengguna</h2><ol class="list-decimal space-y-2 pl-5"><li>Buka Manajemen akun, lalu pilih Tambah akun.</li><li>Isi nama, username, email bila diperlukan, role, dan password awal.</li><li>Gunakan pencarian atau filter role untuk menemukan akun.</li><li>Pilih Ubah untuk menyesuaikan data, role, atau status aktif akun.</li></ol><p>Reset password mengganti password dan mencabut seluruh sesi akun. Cabut sesi meminta pengguna masuk kembali tanpa mengganti password. Akun nonaktif tidak dapat masuk.</p><p class="text-ink-500">Hanya administrator dapat mengelola akun administrator. Role dan status aktif akun sendiri dilindungi dari perubahan.</p><NuxtLink to="/admin/system" class="btn btn-outline">Buka manajemen akun</NuxtLink></section>
    <section v-if="local && can('roles.manage')" id="roles" class="klh-card scroll-mt-24 space-y-3 p-5 sm:p-8"><h2 class="font-display text-2xl font-bold">Roles &amp; hak akses</h2><p>Sistem menyediakan tiga role: Administrator, Pengelola, dan Publik. Administrator memiliki seluruh izin. Izin Pengelola dan Publik dapat disesuaikan oleh administrator.</p><ol class="list-decimal space-y-2 pl-5"><li>Buka Roles &amp; hak akses dan lihat kartu role yang ingin diatur.</li><li>Centang izin yang diperlukan, lalu pilih Simpan hak akses.</li><li>Pengguna dengan role tersebut perlu masuk kembali agar menggunakan izin terbaru.</li></ol><p class="text-ink-500">Izin Manajemen hak akses memberi akses untuk melihat matriks role; penyimpanan perubahan tetap khusus administrator. Gunakan Batalkan perubahan untuk mengembalikan pilihan sebelum disimpan.</p><NuxtLink to="/admin/roles" class="btn btn-outline">Buka manajemen roles</NuxtLink></section>
    <section v-if="local && can('audit.view')" class="klh-card space-y-3 p-5 sm:p-8"><h2 class="font-display text-2xl font-bold">Log aktivitas</h2><p>Buka Manajemen akun dan pilih Log aktivitas untuk melihat hingga 200 aktivitas terbaru, termasuk perubahan profil, akun, password, dan izin. Waktu ditampilkan dalam WIB.</p></section>
    <section id="bantuan" class="klh-card scroll-mt-24 space-y-3 p-5 sm:p-8"><h2 class="font-display text-2xl font-bold">Bantuan akses</h2><p>Jika sesi berakhir, masuk kembali. Jika aplikasi tidak muncul atau akses ditolak, minta administrator memeriksa role dan status akun Anda. Jika data gagal dimuat, periksa koneksi lalu coba kembali.</p><p class="text-ink-500">Jangan kirim password dalam laporan masalah. Cukup sampaikan nama halaman dan pesan kesalahan yang muncul.</p></section>
  </div>
</template>
